
import { Question } from '../types';

export const GRADE_5_QUESTIONS: Question[] = [
  // --- MATHEMATICS ---
  {
    id: 'g5-math-1',
    text: 'Write the numeral: Six Lakh, Four Thousand and Five.',
    options: ['6,40,005', '6,04,005', '6,40,050', '6,04,500'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Numbers',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-2',
    text: 'The place value of 9 in 5,92,100 is:',
    options: ['900', '9,000', '90,000', '9 Lakh'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Place Value',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-3',
    text: 'Round off 4,567 to the nearest 100.',
    options: ['4,500', '4,600', '5,000', '4,570'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Estimations',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-4',
    text: 'Which symbol makes this true? 50,090 ___ 50,900',
    options: ['>', '<', '=', 'None'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Comparing Numbers',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-5',
    text: 'Successor of 99,999 is:',
    options: ['99,998', '1,00,000', '1,00,001', '10,000'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Numbers',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-6',
    text: 'In Division: Dividend = Divisor × ____ (if Remainder is 0)',
    options: ['Remainder', 'Quotient', 'Sum', 'Zero'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Division',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-7',
    text: '500 × 50 = ?',
    options: ['2500', '250', '25000', '50050'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Multiplication',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-8',
    text: 'If 1 kg sugar costs 40, what is the cost of 15 kg?',
    options: ['600', '500', '400', '150'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Money',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-9',
    text: '0 ÷ 15 = ?',
    options: ['15', '0', '1', 'Cannot be done'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Division',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-10',
    text: '15 ÷ 0 = ?',
    options: ['15', '0', '1', 'Not Defined'],
    correctAnswer: 3,
    difficulty: 3,
    skill: 'Division',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-11',
    text: 'Which of these is a Prime Number?',
    options: ['9', '15', '13', '21'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Number Theory',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-12',
    text: 'The smallest Factor of any number is:',
    options: ['0', '1', 'The number itself', '2'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Factors',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-13',
    text: 'LCM of 4 and 6 is:',
    options: ['24', '12', '2', '10'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'LCM/HCF',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-14',
    text: 'Is 24 a multiple of 5?',
    options: ['Yes', 'No'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Multiples',
    grade: '5',
    subject: 'Math',
    damage: 10
  },
  {
    id: 'g5-math-15',
    text: 'The HCF of 10 and 20 is:',
    options: ['10', '20', '5', '2'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'LCM/HCF',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-16',
    text: 'Which fraction is Equivalent to 1/2?',
    options: ['2/5', '3/6', '4/9', '1/3'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-17',
    text: '2/7 + 3/7 = ?',
    options: ['5/14', '5/7', '6/7', '1/7'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-18',
    text: 'Arrange in Ascending order: 1/5, 1/2, 1/9',
    options: ['1/9, 1/5, 1/2', '1/2, 1/5, 1/9', '1/5, 1/2, 1/9', '1/9, 1/2, 1/5'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g5-math-19',
    text: 'What kind of fraction is 7/4?',
    options: ['Proper', 'Improper', 'Mixed', 'Unit'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-20',
    text: 'Convert Mixed Fraction 1 1/2 to Improper:',
    options: ['2/2', '3/2', '1/2', '4/2'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-21',
    text: 'A line that goes through the center of a circle is called:',
    options: ['Radius', 'Chord', 'Diameter', 'Arc'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-22',
    text: 'The boundary length of a shape is called its:',
    options: ['Area', 'Perimeter', 'Volume', 'Width'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-23',
    text: 'Find the Perimeter of a square with side 5cm.',
    options: ['25 cm', '20 cm', '10 cm', '15 cm'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-24',
    text: 'Identify the shape: Parallelogram',
    options: ['Rectangle', 'Parallelogram', 'Square', 'Triangle'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-25',
    text: 'If Radius is 4cm, Diameter is?',
    options: ['2cm', '4cm', '8cm', '16cm'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-26',
    text: '15:00 hours in 12-hour clock is:',
    options: ['5:00 PM', '3:00 PM', '3:00 AM', '5:00 AM'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Time',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-27',
    text: 'How many days in a Leap Year?',
    options: ['365', '366', '364', '360'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Time',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-28',
    text: 'Add: 2m 50cm + 1m 50cm = ?',
    options: ['3m 100cm', '4m', '3m 50cm', '400 cm'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Measurement',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-29',
    text: 'Calculate duration: 9:00 AM to 1:00 PM.',
    options: ['3 hours', '4 hours', '5 hours', '2 hours'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Time',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-30',
    text: '2500 paise = ____',
    options: ['2.5 Rupees', '25 Rupees', '250 Rupees', '0.25 Rupees'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Money',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-31',
    text: 'In a Bar Graph, the height of the bar represents...',
    options: ['The width', 'The value/quantity', 'The name', 'Nothing'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Data Handling',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-32',
    text: 'Tally marks for 5 is written as:',
    options: ['|||||', '|||| with diagonal', 'V', 'Five'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Data Handling',
    grade: '5',
    subject: 'Math',
    damage: 10
  },
  {
    id: 'g5-math-33',
    text: 'Pattern: 1, 4, 9, 16, __',
    options: ['20', '25', '24', '18'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Patterns',
    grade: '5',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g5-math-34',
    text: 'Half of a Quarter is?',
    options: ['1/8', '1/2', '1/6', '1/4'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-35',
    text: 'Which is heavier? 1kg or 900g?',
    options: ['900g', '1kg', 'Equal', 'Depends'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Measurement',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-36',
    text: 'Rectangle: Perimeter = 20cm, Length = 6cm. Find Breadth.',
    options: ['14cm', '4cm', '7cm', '2cm'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g5-math-37',
    text: 'How many Prime numbers are there between 10 and 20?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Number Theory',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-38',
    text: 'What is the angle between clock hands at 6:00 PM?',
    options: ['90 degrees', '180 degrees', '360 degrees', '0 degrees'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-39',
    text: 'I am a number. Multiple of 3, Factor of 18, Greater than 5.',
    options: ['6', '3', '18', '9'],
    correctAnswer: 3,
    difficulty: 3,
    skill: 'Logic',
    grade: '5',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g5-math-40',
    text: 'How many 1/4 (quarters) make 3 wholes?',
    options: ['4', '8', '12', '16'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-41',
    text: 'Product of two numbers is 0. One is 5. What is the other?',
    options: ['5', '1', '0', '10'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Multiplication',
    grade: '5',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g5-math-42',
    text: 'Train leaves at 22:00, arrives at 02:00 next day. Duration?',
    options: ['20 hours', '4 hours', '6 hours', '2 hours'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Time',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-43',
    text: 'Which shape can be made by joining two Triangles?',
    options: ['Circle', 'Square/Rhombus', 'Cylinder', 'Sphere'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-44',
    text: 'Cost Price = 100, Selling Price = 80. Find Loss.',
    options: ['20', '180', '100', 'No Loss'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Money',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-45',
    text: 'Roman Numeral for 49 is:',
    options: ['IL', 'XLIX', 'XXXXIX', 'LIX'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Roman Numerals',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-46',
    text: 'Box Area = 24 sq cm. Length = 6cm. Perimeter = ?',
    options: ['4cm', '10cm', '20cm', '24cm'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Geometry',
    grade: '5',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g5-math-47',
    text: 'Divide 100 by half (1/2).',
    options: ['50', '200', '2', '100'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Fractions',
    grade: '5',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g5-math-48',
    text: 'What is the sum of the first 3 Odd numbers?',
    options: ['3', '6', '9', '12'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Numbers',
    grade: '5',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g5-math-49',
    text: 'Bottle = 500ml. How many to fill 2L bucket?',
    options: ['2', '4', '5', '10'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Measurement',
    grade: '5',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g5-math-50',
    text: 'Find missing operations: 5 __ 5 __ 5 = 5',
    options: ['+, -', 'x, ÷', '-, +', 'All of the above'],
    correctAnswer: 3,
    difficulty: 3,
    skill: 'Logic',
    grade: '5',
    subject: 'Math',
    damage: 30
  },

  // --- SCIENCE ---
  {
    id: 'g5-sci-1',
    text: 'The process by which plants make food is called:',
    options: ['Digestion', 'Photosynthesis', 'Respiration', 'Absorption'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-2',
    text: 'Which gas do plants take IN to make food?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-3',
    text: 'The green substance in leaves is:',
    options: ['Stomata', 'Chlorophyll', 'Starch', 'Glucose'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-4',
    text: 'Plants that grow in water are called:',
    options: ['Terrestrial', 'Aquatic', 'Desert', 'Mountain'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-5',
    text: 'Mushrooms are not plants because...',
    options: ['They are small', 'They have no chlorophyll', 'They eat bugs', 'They live in dark'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Fungi',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-6',
    text: 'Why do Polar Bears have thick fur?',
    options: ['To look big', 'To keep warm', 'To swim fast', 'To hide'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Adaptation',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-7',
    text: 'Animals that lay eggs are called:',
    options: ['Mammals', 'Oviparous', 'Viviparous', 'Reptiles'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Animals',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-8',
    text: 'Which animal uses Camouflage?',
    options: ['Elephant', 'Chameleon', 'Dog', 'Cow'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Animals',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-9',
    text: 'A tadpole breathes through:',
    options: ['Lungs', 'Gills', 'Skin', 'Nose'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Animals',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-10',
    text: 'Digestion begins in the:',
    options: ['Stomach', 'Mouth', 'Intestine', 'Liver'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Human Body',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-11',
    text: 'Which teeth are used for tearing food?',
    options: ['Incisors', 'Canines', 'Molars', 'Premolars'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Human Body',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-12',
    text: 'The tube connecting mouth to stomach is:',
    options: ['Windpipe', 'Oesophagus', 'Intestine', 'Nerve'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Human Body',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-13',
    text: 'Microbes that cause disease are called:',
    options: ['Germs', 'Vitamins', 'Cells', 'Probiotics'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Health',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-14',
    text: 'In a Sugar solution, Sugar is the:',
    options: ['Solvent', 'Solute', 'Solution', 'Liquid'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Chemistry',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-15',
    text: 'Method to separate salt from water:',
    options: ['Filtration', 'Evaporation', 'Decantation', 'Sedimentation'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Chemistry',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-16',
    text: 'Molecules are packed tightest in:',
    options: ['Solids', 'Liquids', 'Gases', 'Water'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Matter',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-17',
    text: 'Changing Water Vapor to Water is:',
    options: ['Evaporation', 'Condensation', 'Melting', 'Boiling'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Matter',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-18',
    text: 'Force can change an object\'s:',
    options: ['Shape', 'Speed', 'Direction', 'All of the above'],
    correctAnswer: 3,
    difficulty: 2,
    skill: 'Force',
    grade: '5',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g5-sci-19',
    text: 'Which force pulls everything down to Earth?',
    options: ['Magnetic', 'Friction', 'Gravity', 'Muscular'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Force',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-20',
    text: 'Rough surfaces create _____ friction than smooth surfaces.',
    options: ['Less', 'More', 'Equal', 'No'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Force',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-21',
    text: 'Energy from the Sun is called:',
    options: ['Lunar Energy', 'Solar Energy', 'Hydro Energy', 'Wind Energy'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Energy',
    grade: '5',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g5-sci-22',
    text: 'Rotation of Earth causes:',
    options: ['Seasons', 'Day and Night', 'Rain', 'Eclipses'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Space',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-23',
    text: 'Imaginary line dividing Earth into North and South:',
    options: ['Axis', 'Equator', 'Orbit', 'Pole'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Space',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-24',
    text: 'The largest planet is:',
    options: ['Earth', 'Jupiter', 'Saturn', 'Mars'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Space',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-25',
    text: 'Soil formed from dead plants/animals is rich in:',
    options: ['Clay', 'Humus', 'Sand', 'Rocks'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Environment',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-26',
    text: 'Which is a biodegradable waste?',
    options: ['Plastic bottle', 'Banana Peel', 'Glass', 'Metal can'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Environment',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-27',
    text: '3 Rs: Reduce, Reuse, ____.',
    options: ['Remake', 'Recycle', 'Return', 'Run'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Environment',
    grade: '5',
    subject: 'Science',
    damage: 10
  },
  {
    id: 'g5-sci-28',
    text: 'First Aid for a minor burn:',
    options: ['Hot water', 'Cold running water', 'Oil', 'Bandage tightly'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Safety',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-29',
    text: 'Which clothes keep us cool?',
    options: ['Wool', 'Dark colors', 'Cotton/Light colors', 'Silk'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Materials',
    grade: '5',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g5-sci-30',
    text: 'Air is a mixture of:',
    options: ['Solids', 'Gases', 'Liquids', 'Nothing'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Matter',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-31',
    text: 'Plants breathe through tiny holes called:',
    options: ['Cells', 'Stomata', 'Pores', 'Gills'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Plants',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-32',
    text: 'Which is NOT a planet?',
    options: ['Mars', 'Moon', 'Saturn', 'Earth'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Space',
    grade: '5',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g5-sci-33',
    text: 'Water freezing point is:',
    options: ['100°C', '0°C', '50°C', '10°C'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Matter',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-34',
    text: 'Mosquitoes spread which disease?',
    options: ['Flu', 'Malaria/Dengue', 'Typhoid', 'Covid'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Health',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-35',
    text: 'What covers 70% of Earth?',
    options: ['Land', 'Water', 'Forest', 'Ice'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Earth',
    grade: '5',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g5-sci-36',
    text: 'If you cover a plant with a blanket for 1 week:',
    options: ['It grows faster', 'It turns yellow/pale', 'Nothing', 'It flowers'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Plants',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-37',
    text: 'Why does a steel ship float but a nail sinks?',
    options: ['Engine', 'Buoyancy/Shape', 'Salty water', 'Weight'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Force',
    grade: '5',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g5-sci-38',
    text: 'In a spaceship, you drop a pen. What happens?',
    options: ['Falls down', 'Floats', 'Flies up', 'Breaks'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Space',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-39',
    text: 'Why sprinkle salt on icy roads?',
    options: ['Melt ice', 'Make it white', 'Kill insects', 'Increase friction'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Chemistry',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-40',
    text: 'If snakes disappear, rat population will:',
    options: ['Decrease', 'Increase', 'Stay same', 'Become snakes'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Ecosystem',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-41',
    text: 'Why can\'t we drink ocean water?',
    options: ['Dirty', 'Too much salt', 'Fish live in it', 'Blue'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Environment',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-42',
    text: 'Wet cloth dries faster on windy day because:',
    options: ['Wind blows water', 'Evaporation increases', 'Wind is hot', 'Cloth shakes'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Matter',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-43',
    text: 'Which jar has the most oxygen?',
    options: ['Jar with mouse', 'Jar with plant', 'Jar with candle', 'Empty sealed jar'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Plants',
    grade: '5',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g5-sci-44',
    text: 'Why are pan handles made of plastic?',
    options: ['Cheap', 'Plastic insulates heat', 'Strong', 'Look good'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Heat',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-45',
    text: 'If Earth stopped rotating, what happens to Day/Night?',
    options: ['24 hr days', 'Permanent Day/Night sides', 'No change', 'Explosion'],
    correctAnswer: 1,
    difficulty: 3, // Hard
    skill: 'Space',
    grade: '5',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g5-sci-46',
    text: 'Water drops on outside of cold glass come from:',
    options: ['Leak', 'Condensation of air vapor', 'Melted ice', 'Magic'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Matter',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-47',
    text: 'Which soil is best for growing cotton?',
    options: ['Sandy', 'Clayey (Black)', 'Rocky', 'Gravel'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Agriculture',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-48',
    text: 'Why do camels have long eyelashes?',
    options: ['Look pretty', 'Keep sand out', 'See at night', 'Scare flies'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Adaptation',
    grade: '5',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g5-sci-49',
    text: 'Sound cannot travel through:',
    options: ['Water', 'Wood', 'Vacuum', 'Air'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Sound',
    grade: '5',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g5-sci-50',
    text: 'Mixing Blue and Yellow paint to get Green is:',
    options: ['Chemical change', 'Physical mixture', 'New substance', 'Unknown'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Chemistry',
    grade: '5',
    subject: 'Science',
    damage: 25
  },

  // --- ENGLISH ---
  {
    id: 'g5-eng-1',
    text: 'Identify Adverb: "The tortoise moved slowly."',
    options: ['Tortoise', 'Moved', 'Slowly', 'The'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-2',
    text: 'Identify Adjective: "She wore a beautiful blue dress."',
    options: ['Wore', 'Beautiful', 'She', 'Dress'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-3',
    text: 'Plural of "Tooth":',
    options: ['Tooths', 'Teeth', 'Teeths', 'Teeth\'s'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-4',
    text: '"A _____ of fish." (Collective Noun)',
    options: ['Pack', 'School/Shoal', 'Herd', 'Bunch'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-5',
    text: 'Which sentence is in Future Tense?',
    options: ['I play cricket.', 'I played cricket.', 'I will play cricket.', 'I am playing.'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Tenses',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-6',
    text: '"The dog hurt _____."',
    options: ['Itself', 'Himself', 'Themselves', 'Myself'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Pronouns',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-7',
    text: '"Honesty is the best policy." Honesty is:',
    options: ['Common Noun', 'Proper Noun', 'Abstract Noun', 'Collective Noun'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Nouns',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-8',
    text: '"I was sick _____ I went to the doctor."',
    options: ['Because', 'So', 'But', 'Or'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Conjunctions',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-9',
    text: '"The book is _____ the table." (Underneath)',
    options: ['On', 'Under', 'Over', 'At'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Prepositions',
    grade: '5',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g5-eng-10',
    text: 'Correct spelling:',
    options: ['Receive', 'Recieve', 'Riceive', 'Receve'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Spelling',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-11',
    text: 'Antonym of "Ancient":',
    options: ['Old', 'Modern', 'Historical', 'Past'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-12',
    text: 'Synonym of "Happy":',
    options: ['Sad', 'Joyful', 'Angry', 'Tired'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g5-eng-13',
    text: 'Homophone: "I _____ the ball."',
    options: ['Threw', 'Through', 'Thorough', 'True'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-14',
    text: 'Person who writes books is:',
    options: ['Editor', 'Author', 'Actor', 'Artist'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-15',
    text: '"Let the cat out of the bag" means:',
    options: ['Free a pet', 'Reveal a secret', 'Go shopping', 'Lose something'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Idioms',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-16',
    text: 'Good, Better, _____',
    options: ['Best', 'Goodest', 'Most Good', 'Bestest'],
    correctAnswer: 0,
    difficulty: 1,
    skill: 'Adjectives',
    grade: '5',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g5-eng-17',
    text: 'Horse : Mare :: Bull : ?',
    options: ['Calf', 'Cow', 'Ox', 'Buffalo'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Analogy',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-18',
    text: 'Identify Subject: "The big yellow bus stopped."',
    options: ['Stopped', 'The big yellow bus', 'Yellow', 'Bus stopped'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-19',
    text: 'Which word has a prefix?',
    options: ['Understand', 'Unhappy', 'Uncle', 'Under'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-20',
    text: '"This is my pen." "My" is:',
    options: ['Verb', 'Possessive Adjective', 'Noun', 'Conjunction'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-21',
    text: 'Choose correct sentence:',
    options: ['He don\'t like apples.', 'He doesn\'t like apples.', 'He not like apples.', 'He no like apples.'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-22',
    text: '"Hurrah! We won." This is:',
    options: ['Exclamatory', 'Interrogative', 'Statement', 'Command'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Sentences',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-23',
    text: 'Alphabetical Order: Apple, Ant, Axe, Arrow.',
    options: ['Ant, Apple, Arrow, Axe', 'Apple, Ant, Axe, Arrow', 'Ant, Apple, Axe, Arrow', 'Axe, Arrow, Ant, Apple'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Sorting',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-24',
    text: 'Which word suggests a question?',
    options: ['There', 'Why', 'Because', 'Then'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 10
  },
  {
    id: 'g5-eng-25',
    text: '"The mice ran away." (Change to Singular)',
    options: ['The mouses ran away.', 'The mouse runs away.', 'The mouse ran away.', 'The mice runs away.'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-26',
    text: '"Precious" means:',
    options: ['Cheap', 'Heavy', 'Valuable', 'Shiny'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-27',
    text: 'Punctuate: "where are you going"',
    options: ['Where are you going.', 'Where are you going!', 'Where are you going?', 'where are you going?'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Punctuation',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-28',
    text: '"As brave as a ____"',
    options: ['Lion', 'Dog', 'Mouse', 'Cat'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Similes',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-29',
    text: '"He is poor _____ he is happy."',
    options: ['And', 'So', 'But', 'Or'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Conjunctions',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-30',
    text: 'Which is a Complex sentence?',
    options: ['I like tea.', 'I like tea and coffee.', 'I went home because I was tired.', 'I ran.'],
    correctAnswer: 2,
    difficulty: 3, // Harder
    skill: 'Sentences',
    grade: '5',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g5-eng-31',
    text: '"I saw a flok of sheep." Spot error.',
    options: ['Saw', 'Flok', 'Sheep', 'A'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Spelling',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-32',
    text: '"Do you have _____ money?"',
    options: ['Many', 'Any', 'Few', 'A'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-33',
    text: '"The baby is crying." Tense?',
    options: ['Simple Present', 'Present Continuous', 'Past', 'Future'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Tenses',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-34',
    text: '"Go away!" This is an:',
    options: ['Advice', 'Request', 'Order', 'Question'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Sentences',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-35',
    text: '"Write" vs "Right". These are:',
    options: ['Synonyms', 'Antonyms', 'Homophones', 'Pronouns'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-36',
    text: '"I helped him." Change to Passive.',
    options: ['He is helped by me.', 'He was helped by me.', 'I was helping him.', 'He helps me.'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Voice',
    grade: '5',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g5-eng-37',
    text: 'Correct order: "Yesterday / to the market / went / I"',
    options: ['Yesterday went I to the market.', 'I went to the market yesterday.', 'To the market I went yesterday.', 'Yesterday I market went.'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Sentences',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-38',
    text: 'Which sentence implies speaker is annoyed?',
    options: ['It\'s raining again!', 'It\'s raining again.', 'It\'s raining again?', 'It\'s raining.'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Tone',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-39',
    text: '"She is the _____ of the two sisters."',
    options: ['Tallest', 'Taller', 'Tall', 'Most tall'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Adjectives',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-40',
    text: '"I haven\'t got _____ money."',
    options: ['No', 'Any', 'Some', 'Many'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-41',
    text: '"He is an honest man." Why "An"?',
    options: ['H is a vowel', 'H is silent', 'Rule exception', 'Mistake'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Articles',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-42',
    text: 'Teacher : Student :: Doctor : ?',
    options: ['Hospital', 'Nurse', 'Patient', 'Medicine'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Analogy',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-43',
    text: '"The wind howled." Example of:',
    options: ['Personification', 'Simile', 'Rhyme', 'Fact'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Literary Devices',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-44',
    text: 'Redundant word in: "Please repeat it again."',
    options: ['Please', 'Repeat', 'Again', 'It'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-45',
    text: '"You _____ wear a helmet." (Strong advice)',
    options: ['Can', 'May', 'Must', 'Might'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Modals',
    grade: '5',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g5-eng-46',
    text: '"Despite being tired, he worked." Meaning?',
    options: ['Stopped working', 'Worked because tired', 'Worked even though tired', 'Isn\'t tired'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Comprehension',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-47',
    text: 'Which word has a different vowel sound?',
    options: ['Cut', 'Put', 'Hut', 'Shut'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Phonetics',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-48',
    text: '"If I were a bird, I _____ fly."',
    options: ['Will', 'Can', 'Would', 'Shall'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Conditionals',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-49',
    text: '"Stationery" vs "Stationary". Writing items?',
    options: ['Stationary', 'Stationery', 'Both', 'None'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Vocabulary',
    grade: '5',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g5-eng-50',
    text: '"The man who is wearing red..." "Who" is:',
    options: ['Question', 'Relative Pronoun', 'Adjective', 'Verb'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '5',
    subject: 'English',
    damage: 25
  },
];
