
import { Question } from '../types';

export const GRADE_7_QUESTIONS: Question[] = [
  // --- MATHEMATICS ---
  {
    id: 'g7-math-1',
    text: 'Which integer is smaller?',
    options: ['-1', '-10', '0', '1'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-2',
    text: '(+5) + (-3) = ?',
    options: ['8', '2', '-2', '-8'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-3',
    text: 'The opposite of "Going 5km North" is:',
    options: ['Going 5km East', 'Going 5km South', 'Coming back', 'Going 5km Up'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-4',
    text: 'Arrange in Ascending Order: 0, -5, 2, -1',
    options: ['-5, -1, 0, 2', '0, -1, -5, 2', '2, 0, -1, -5', '-1, -5, 0, 2'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-5',
    text: 'Predecessor of -1 is:',
    options: ['0', '-2', '1', '-1.1'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-6',
    text: 'If x = 3, what is 2x + 1?',
    options: ['6', '7', '5', '4'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g7-math-7',
    text: '"5 added to y" is written as:',
    options: ['5y', 'y + 5', 'y - 5', '5/y'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-8',
    text: 'Solve for x: x + 4 = 10',
    options: ['14', '6', '4', '40'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-9',
    text: 'A variable is:',
    options: ['A fixed number', 'A symbol that changes value', 'An equal sign', 'A shape'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-10',
    text: 'Which is an equation?',
    options: ['x + 5', '2x > 4', 'x - 2 = 7', '5 + 2'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-11',
    text: '2/3 of 18 is:',
    options: ['6', '9', '12', '15'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Fractions',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-12',
    text: 'Which is an Improper Fraction?',
    options: ['2/3', '5/4', '1/2', '7/9'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Fractions',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-13',
    text: '2.5 × 0.2 = ?',
    options: ['5.0', '0.5', '0.05', '50'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Decimals',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-14',
    text: 'Reduce to simplest form: 12/16',
    options: ['6/8', '3/4', '12/4', '4/3'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Fractions',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-15',
    text: '5 + 3/10 + 4/100 as a decimal:',
    options: ['5.34', '5.304', '53.4', '0.534'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Decimals',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-16',
    text: 'Ratio of 50cm to 1m is:',
    options: ['50:1', '1:2', '1:50', '2:1'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Ratio',
    grade: '7',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g7-math-17',
    text: 'If 3 pens cost 15, cost of 5 pens?',
    options: ['20', '25', '30', '35'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Unitary Method',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-18',
    text: 'Are 2, 4, 6, 12 in proportion?',
    options: ['Yes', 'No'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Ratio',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-19',
    text: 'Simplest form of 20:30',
    options: ['20:30', '2:3', '4:6', '10:15'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Ratio',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-20',
    text: 'Divide 20 chocolates in ratio 2:3.',
    options: ['10, 10', '8, 12', '5, 15', '2, 18'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Ratio',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-21',
    text: 'Triangle with no equal sides:',
    options: ['Equilateral', 'Isosceles', 'Scalene', 'Right'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-22',
    text: 'Identify Parallel Lines:',
    options: ['Intersecting', 'Perpendicular', 'Parallel', 'Curved'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-23',
    text: 'An angle measuring 180 degrees is:',
    options: ['Right', 'Reflex', 'Straight', 'Complete'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-24',
    text: 'Perpendicular lines meet at:',
    options: ['45°', '90°', '180°', '60°'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-25',
    text: 'Which is a Polygon?',
    options: ['Circle', 'Triangle', 'Cylinder', 'Cone'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-26',
    text: 'Perimeter of regular pentagon (side 3cm):',
    options: ['9cm', '12cm', '15cm', '18cm'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Mensuration',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-27',
    text: 'Area of rectangle (L=4m, B=3m):',
    options: ['12 m²', '7 m²', '14 m²', '12 m'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Mensuration',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-28',
    text: 'Scale: 1 unit = 10 students. Bar height 5 units = ?',
    options: ['5', '15', '50', '100'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Data Handling',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-29',
    text: 'Diameter is _____ times the Radius.',
    options: ['2', '3', '1/2', '4'],
    correctAnswer: 0,
    difficulty: 1,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g7-math-30',
    text: 'To fence a field, we need:',
    options: ['Area', 'Perimeter', 'Volume', 'Length'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Mensuration',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-31',
    text: '-10 is _____ -5.',
    options: ['Greater than', 'Less than', 'Equal to', 'Positive'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-32',
    text: 'Additive Inverse of -7 is:',
    options: ['-7', '0', '7', '1/7'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-33',
    text: 'How many lines pass through one point?',
    options: ['One', 'Two', 'Infinite', 'Zero'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-34',
    text: '1 Million = _____ Lakhs.',
    options: ['1', '10', '100', '1000'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Numbers',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-35',
    text: '13.5 + 1.5 = ?',
    options: ['14', '15', '15.5', '13.515'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Decimals',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-36',
    text: '(-5) + (+2) - (-3) = ?',
    options: ['-6', '0', '-4', '4'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Integers',
    grade: '7',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g7-math-37',
    text: 'L=2B. Perimeter=30cm. Find Length.',
    options: ['5cm', '10cm', '15cm', '20cm'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-38',
    text: 'Angles on straight line: 40°, 90°, x. Find x.',
    options: ['40°', '50°', '60°', '130°'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g7-math-39',
    text: 'Which ratio is larger: 3:4 or 5:6?',
    options: ['3:4', '5:6', 'Equal', 'Cannot say'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Ratio',
    grade: '7',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g7-math-40',
    text: 'Sum of 3 consecutive integers is 12. Middle integer?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-41',
    text: 'Room 5x4m. Carpet 3x3m. Uncarpeted Area?',
    options: ['11 m²', '20 m²', '9 m²', '29 m²'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Mensuration',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-42',
    text: 'If a=2, b=-1. Find a - b + ab',
    options: ['1', '5', '3', '-1'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-43',
    text: 'Matchsticks for "n" squares in a row:',
    options: ['4n', '3n + 1', '4n - 1', '2n + 2'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Patterns',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-44',
    text: '1/3 of x is 5 less than 1/2 of x. Find x.',
    options: ['15', '30', '60', '10'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 35
  },
  {
    id: 'g7-math-45',
    text: 'Which number has exactly 3 factors?',
    options: ['4', '6', '7', '12'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Number Theory',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-46',
    text: 'Travel 60km in 1.5 hrs. Speed?',
    options: ['45 km/h', '40 km/h', '90 km/h', '30 km/h'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Speed',
    grade: '7',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g7-math-47',
    text: 'Complement of 35°?',
    options: ['145°', '55°', '65°', '35°'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Geometry',
    grade: '7',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g7-math-48',
    text: 'Multiply by -1, subtract 5, result -10. Number?',
    options: ['5', '-5', '15', '-15'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Algebra',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-49',
    text: 'Total Surface Area of cube = 24. Side?',
    options: ['4', '2', '3', '1'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Mensuration',
    grade: '7',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g7-math-50',
    text: 'a(b+c) = ab + ac. Property?',
    options: ['Commutative', 'Associative', 'Distributive', 'Closure'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Properties',
    grade: '7',
    subject: 'Math',
    damage: 20
  },

  // --- SCIENCE ---
  {
    id: 'g7-sci-1',
    text: 'Motion of a pendulum is:',
    options: ['Rectilinear', 'Periodic', 'Circular', 'Random'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Physics',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-2',
    text: 'Material that allows current to pass:',
    options: ['Rubber', 'Copper', 'Wood', 'Plastic'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Electricity',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-3',
    text: 'Shadows form because light travels in...',
    options: ['Curves', 'Straight lines', 'Zig-zag', 'Circles'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Light',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-4',
    text: 'Unlike poles of a magnet (N-S):',
    options: ['Repel', 'Attract', 'Nothing', 'Heat up'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Magnetism',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-5',
    text: 'SI unit of length:',
    options: ['Centimeter', 'Meter', 'Kilometer', 'Foot'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Measurement',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-6',
    text: 'Which part of a bulb glows?',
    options: ['Glass', 'Filament', 'Base', 'Wire'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Electricity',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-7',
    text: 'Image in Pinhole Camera is:',
    options: ['Erect', 'Inverted', 'Invisible', 'B&W'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Light',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-8',
    text: 'Which fibre is natural?',
    options: ['Nylon', 'Polyester', 'Cotton', 'Acrylic'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Materials',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-9',
    text: 'Separating grains from stalks:',
    options: ['Handpicking', 'Threshing', 'Sieving', 'Filtration'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Separation',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-10',
    text: 'Melting of Ice is:',
    options: ['Chemical', 'Reversible', 'Irreversible', 'Biological'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Changes',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-11',
    text: 'Which is Translucent?',
    options: ['Wood', 'Glass', 'Butter Paper', 'Mirror'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Light',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-12',
    text: 'Burning of paper is:',
    options: ['Physical', 'Reversible', 'Irreversible', 'Temporary'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Changes',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-13',
    text: 'Solution where no more solute dissolves:',
    options: ['Dilute', 'Saturated', 'Pure', 'Warm'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Chemistry',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-14',
    text: 'Jute comes from:',
    options: ['Leaf', 'Stem', 'Root', 'Fruit'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-15',
    text: 'Vitamin A deficiency causes:',
    options: ['Beri-beri', 'Night Blindness', 'Scurvy', 'Rickets'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Health',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-16',
    text: 'Nutrient providing most energy:',
    options: ['Vitamins', 'Fats', 'Minerals', 'Water'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Nutrition',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-17',
    text: 'Fixed joints are in:',
    options: ['Knee', 'Skull', 'Finger', 'Neck'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Body',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-18',
    text: 'Earthworms breathe via:',
    options: ['Lungs', 'Gills', 'Skin', 'Nose'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Animals',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-19',
    text: 'Cactus spines are modified:',
    options: ['Flowers', 'Leaves', 'Roots', 'Fruits'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Adaptation',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-20',
    text: 'Lives without water for days:',
    options: ['Tiger', 'Camel', 'Horse', 'Elephant'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Adaptation',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-21',
    text: 'Main root is called:',
    options: ['Fibrous', 'Tap root', 'Lateral', 'Hair'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-22',
    text: 'Snails move using:',
    options: ['Leg', 'Foot', 'Fin', 'Wing'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Animals',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-23',
    text: 'Vermicomposting uses:',
    options: ['Chemicals', 'Redworms', 'Plastic', 'Fire'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Environment',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-24',
    text: 'Gas supporting burning:',
    options: ['Nitrogen', 'Oxygen', 'CO2', 'Argon'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Chemistry',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-25',
    text: 'Rainwater harvesting:',
    options: ['Drain it', 'Collect it', 'Measure it', 'Play'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Environment',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-26',
    text: 'Which waste decays?',
    options: ['Glass', 'Veg Peels', 'Plastic', 'Metal'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Environment',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-27',
    text: 'Floods caused by:',
    options: ['No rain', 'Heavy rain', 'Wind', 'Heat'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Weather',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-28',
    text: 'Layer of air around Earth:',
    options: ['Hydrosphere', 'Atmosphere', 'Lithosphere', 'Biosphere'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Earth',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-29',
    text: 'Lodestone is natural:',
    options: ['Rock', 'Magnet', 'Wood', 'Metal'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Magnetism',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-30',
    text: 'Device to break circuit:',
    options: ['Bulb', 'Switch', 'Wire', 'Cell'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Electricity',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-31',
    text: '1 Km = ____ Meters',
    options: ['100', '1000', '10', '500'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Measurement',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-32',
    text: 'Goitre caused by lack of:',
    options: ['Iron', 'Iodine', 'Calcium', 'Vitamin C'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Health',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-33',
    text: 'Starch turns Iodine:',
    options: ['Blue-Black', 'Red', 'Yellow', 'Green'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Chemistry',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-34',
    text: 'Elbow to fingertip measure:',
    options: ['Foot', 'Cubit', 'Pace', 'Handspan'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Measurement',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-35',
    text: 'Sinking objects density is:',
    options: ['Lower', 'Higher', 'Same', 'Zero'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Physics',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-36',
    text: 'Compass points North because:',
    options: ['Earth is Magnet', 'Needle heavy', 'Air pushes', 'Gravity'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Magnetism',
    grade: '7',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g7-sci-37',
    text: 'Switch ON, Bulb OFF. Why?',
    options: ['Switch plastic', 'Filament broken', 'Wire copper', 'Cell new'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Electricity',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-38',
    text: 'Mirror Image vs Pinhole Image:',
    options: ['Inverted vs Erect', 'Lateral Inversion vs Inverted', 'Same', 'No color'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Light',
    grade: '7',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g7-sci-39',
    text: 'Separate Salt+Sand+Iron:',
    options: ['Water, Filter', 'Magnet, Water, Filter, Evaporate', 'Handpick', 'Sieve'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Separation',
    grade: '7',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g7-sci-40',
    text: 'Why Moon phases?',
    options: ['Earth Shadow', 'See sun-lit part', 'Shape changes', 'Clouds'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Space',
    grade: '7',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g7-sci-41',
    text: 'Blowing candle puts it out because:',
    options: ['CO2', 'Lowers Temp', 'Cuts Oxygen', 'Magic'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Chemistry',
    grade: '7',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g7-sci-42',
    text: 'Magnet attract plastic?',
    options: ['Yes', 'No', 'Static', 'Only N pole'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Magnetism',
    grade: '7',
    subject: 'Science',
    damage: 10
  },
  {
    id: 'g7-sci-43',
    text: 'Why breathe fast after run?',
    options: ['Lungs tired', 'Need Oxygen', 'Cool down', 'Heart beat'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Body',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-44',
    text: 'Roots down, Stems up. Why?',
    options: ['Geotropism/Phototropism', 'Soil heavy', 'Darkness', 'Chance'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Plants',
    grade: '7',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g7-sci-45',
    text: 'Water freezes -> Volume?',
    options: ['Decreases', 'Increases', 'Same', 'Zero'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Matter',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-46',
    text: 'Heat metal rim for wheel. Why?',
    options: ['Clean', 'Expand then Contract', 'Soft', 'Color'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Heat',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-47',
    text: 'Longer to decompose:',
    options: ['Paper', 'Plastic', 'Same', 'None'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Environment',
    grade: '7',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g7-sci-48',
    text: 'Cant see through bent pipe:',
    options: ['Light straight lines', 'Pipe dark', 'Eye fixed', 'Light slow'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Light',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-49',
    text: 'Fish die in boiled water:',
    options: ['Toxic', 'No Oxygen', 'No Food', 'Soft'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Water',
    grade: '7',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g7-sci-50',
    text: 'N-Pole faces N-Pole:',
    options: ['Touch', 'Repel'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Magnetism',
    grade: '7',
    subject: 'Science',
    damage: 15
  },

  // --- ENGLISH ---
  {
    id: 'g7-eng-1',
    text: '"I _____ reading." (Pres Cont)',
    options: ['Am', 'Was', 'Have', 'Were'],
    correctAnswer: 0,
    difficulty: 1,
    skill: 'Tenses',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-2',
    text: 'Past of Write:',
    options: ['Writed', 'Wrote', 'Written', 'Writing'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Verbs',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-3',
    text: '"She _____ completed work." (Perfect)',
    options: ['Have', 'Has', 'Is', 'Was'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Tenses',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-4',
    text: '"They were _____ football."',
    options: ['Play', 'Playing', 'Played', 'Plays'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Tenses',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-5',
    text: 'Habit Sentence:',
    options: ['I go to school daily', 'I am going to school'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Tenses',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-6',
    text: 'Passive: "Ram eats apple."',
    options: ['Apple eaten by Ram', 'Apple was eaten', 'Ram eating', 'Apple eats Ram'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Voice',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-7',
    text: 'Indirect: He said, "I am happy."',
    options: ['He said he is happy', 'He said that he was happy', 'He says happy', 'He said I happy'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Speech',
    grade: '7',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g7-eng-8',
    text: 'Preposition: "Jumped over wall"',
    options: ['Jumped', 'Over', 'The', 'Wall'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Grammar',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-9',
    text: '"Slowly" is:',
    options: ['Adjective', 'Adverb', 'Noun', 'Verb'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Grammar',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-10',
    text: 'Comparative of Bad:',
    options: ['Badder', 'Worse', 'Worst', 'More Bad'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Adjectives',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-11',
    text: '"This is _____ book." (Possessive)',
    options: ['Mine', 'My', 'Me', 'I'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Pronouns',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-12',
    text: '"Rich _____ unhappy."',
    options: ['And', 'But', 'So', 'Because'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Conjunctions',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-13',
    text: '"A _____ of keys."',
    options: ['Bunch', 'Herd', 'Flock', 'Pack'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-14',
    text: 'Abstract Noun:',
    options: ['Table', 'Kindness', 'School', 'Gold'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Nouns',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-15',
    text: '"You _____ respect elders."',
    options: ['Can', 'Should', 'May', 'Might'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Modals',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-16',
    text: '"What a beautiful flower!"',
    options: ['Statement', 'Exclamatory', 'Interrogative', 'Imperative'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Sentences',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-17',
    text: 'Subject: "The red car is fast."',
    options: ['Car', 'The red car', 'Is', 'Fast'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Sentences',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-18',
    text: 'Order: Always / late / is / he',
    options: ['He is always late', 'Always he is late', 'He always is late', 'Late he is always'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Sentences',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-19',
    text: 'Predicate: "Birds fly in sky."',
    options: ['Birds', 'Fly in sky', 'Sky', 'Fly'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Sentences',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-20',
    text: '"Do you like tea?"',
    options: ['Interrogative', 'Imperative', 'Assertive', 'Negative'],
    correctAnswer: 0,
    difficulty: 1,
    skill: 'Sentences',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-21',
    text: 'Synonym: Vacant',
    options: ['Full', 'Empty', 'Busy', 'Large'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-22',
    text: 'Antonym: Cruel',
    options: ['Mean', 'Kind', 'Angry', 'Happy'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-23',
    text: 'Homophone: Week',
    options: ['Weak', 'Wake', 'Wick', 'Woke'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-24',
    text: 'Treats teeth:',
    options: ['Doctor', 'Dentist', 'Surgeon', 'Nurse'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-25',
    text: 'Prefix for Kind (Negative):',
    options: ['Dis', 'Un', 'In', 'Im'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-26',
    text: 'Let cat out of bag:',
    options: ['Reveal secret', 'Lose pet', 'Shout', 'Run'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Idioms',
    grade: '7',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g7-eng-27',
    text: 'Spelling:',
    options: ['Neccessary', 'Necessary', 'Necesary', 'Nessessary'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Spelling',
    grade: '7',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g7-eng-28',
    text: '"Gold is _____ precious metal."',
    options: ['A', 'An', 'The', 'None'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Articles',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-29',
    text: '"Pen, pencil _____ eraser."',
    options: ['But', 'And', 'Or', 'So'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Conjunctions',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-30',
    text: 'Compound Word:',
    options: ['Window', 'Sunflower', 'Tiger', 'Faster'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-31',
    text: '"Cut _____ knife."',
    options: ['By', 'With', 'From', 'On'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Prepositions',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-32',
    text: 'Past Participle of Eat:',
    options: ['Ate', 'Eaten', 'Eating', 'Eated'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Verbs',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-33',
    text: '"It\'s" stands for:',
    options: ['It is', 'Belonging to it', 'Its', 'It was'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Grammar',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-34',
    text: 'Books kept in:',
    options: ['Lab', 'Library', 'Museum', 'Gym'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    grade: '7',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g7-eng-35',
    text: '"Quickly" describes:',
    options: ['Noun', 'Verb', 'Pronoun', 'Conjunction'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-36',
    text: '"Neither captain nor players _____ present."',
    options: ['Was', 'Were', 'Is', 'Has'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Subject-Verb',
    grade: '7',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g7-eng-37',
    text: '"I wish I _____ a bird."',
    options: ['Am', 'Was', 'Were', 'Be'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Subjunctive',
    grade: '7',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g7-eng-38',
    text: '"Prevented me _____ going."',
    options: ['To', 'From', 'For', 'By'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Prepositions',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-39',
    text: '"Police _____ investigating."',
    options: ['Is', 'Are', 'Was', 'Has'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Subject-Verb',
    grade: '7',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g7-eng-40',
    text: 'Correct:',
    options: ['One of my friend is here', 'One of my friends are here', 'One of my friends is here', 'One of my friend are here'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Grammar',
    grade: '7',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g7-eng-41',
    text: '"He is man _____ I met."',
    options: ['Who', 'Whom', 'Which', 'Whose'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Pronouns',
    grade: '7',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g7-eng-42',
    text: '"Unless you apologize, I _____ forgive."',
    options: ['Will', 'Will not', 'Can', 'Must'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Conditionals',
    grade: '7',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g7-eng-43',
    text: 'Passive: "Who wrote letter?"',
    options: ['Who was letter written?', 'By whom was letter written?', 'Who wrote?', 'By whom letter written?'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Voice',
    grade: '7',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g7-eng-44',
    text: '"Prefer walking _____ swimming."',
    options: ['Than', 'To', 'Over', 'From'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Prepositions',
    grade: '7',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g7-eng-45',
    text: '"Hardly had I arrived _____ it rained."',
    options: ['Than', 'When', 'Then', 'Before'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Conjunctions',
    grade: '7',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g7-eng-46',
    text: '"He died _____ his country."',
    options: ['Of', 'From', 'For', 'By'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Prepositions',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-47',
    text: '"Furniture _____ old."',
    options: ['Are', 'Were', 'Is', 'Have'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Subject-Verb',
    grade: '7',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g7-eng-48',
    text: '"If I had known, I _____ have come."',
    options: ['Will', 'Would', 'Can', 'May'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Conditionals',
    grade: '7',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g7-eng-49',
    text: '"You, he, and I _____ friends."',
    options: ['Am', 'Are', 'Is', 'Was'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Subject-Verb',
    grade: '7',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g7-eng-50',
    text: '"Rolling stone gathers no moss."',
    options: ['Stay still', 'Moving gains no roots', 'Moss bad', 'Rolling good'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Proverbs',
    grade: '7',
    subject: 'English',
    damage: 30
  },
];
