
import { Question } from '../types';

export const GRADE_4_QUESTIONS: Question[] = [
  // --- MATHEMATICS ---
  {
    id: 'g4-math-1',
    text: 'Write the number for: Four thousand, three hundred and six.',
    options: ['4360', '4306', '4036', '436'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Numbers',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-2',
    text: 'What is the Face Value of 7 in 7,128?',
    options: ['7000', '700', '7', '1000'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Place Value',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-3',
    text: 'Which number makes this true: 345 < ___ < 355',
    options: ['340', '360', '350', '345'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Comparing Numbers',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-4',
    text: 'Form the smallest 4-digit number using digits: 5, 0, 9, 2',
    options: ['0259', '2059', '2509', '2590'],
    correctAnswer: 1,
    difficulty: 4, // Logic suggests Medium-Hard
    skill: 'Numbers',
    grade: '4',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g4-math-5',
    text: 'Which number is Even?',
    options: ['1243', '8901', '5678', '3333'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Even/Odd',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-6',
    text: '4500 + 200 = ?',
    options: ['6500', '4700', '4520', '4600'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Addition',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-7',
    text: 'Subtract: 500 - 235',
    options: ['365', '265', '275', '335'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Subtraction',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-8',
    text: '9 + 9 + 9 + 9 is the same as:',
    options: ['9 × 4', '9 + 4', '4 × 4', '9 × 9'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Multiplication',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-9',
    text: '8 × 7 = ?',
    options: ['54', '56', '64', '48'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Multiplication',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-10',
    text: 'Divide 24 sweets among 4 children equally.',
    options: ['8', '4', '6', '10'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Division',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-11',
    text: 'Identify the fraction for a Quarter:',
    options: ['1/2', '1/3', '1/4', '3/4'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Fractions',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-12',
    text: 'Which fraction is the biggest?',
    options: ['1/2', '1/3', '1/4', '1/8'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Fractions',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-13',
    text: 'Half of 20 is?',
    options: ['5', '2', '10', '40'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Division',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-14',
    text: 'How many 50 paise coins make ₹1?',
    options: ['1', '2', '4', '10'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Money',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-15',
    text: '1 Meter = ___ Centimeters?',
    options: ['10', '100', '1000', '50'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Measurement',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-16',
    text: 'Which unit is best to measure the length of a pencil?',
    options: ['Meter', 'Kilometer', 'Centimeter', 'Gram'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Measurement',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-17',
    text: 'Convert 3kg to grams.',
    options: ['300g', '30g', '3000g', '30000g'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Measurement',
    grade: '4',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g4-math-18',
    text: 'How many minutes in 1 hour?',
    options: ['100', '30', '60', '24'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Time',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-19',
    text: 'If the long hand is on 6 and short hand is between 2 and 3, what time is it?',
    options: ['6:15', '2:30', '3:30', '2:06'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Time',
    grade: '4',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g4-math-20',
    text: 'Which month has the fewest days?',
    options: ['January', 'February', 'March', 'April'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Calendar',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-21',
    text: 'A cube has ___ faces.',
    options: ['4', '6', '8', '12'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Geometry',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-22',
    text: 'A circle has ___ corners.',
    options: ['0', '1', '2', 'Infinite'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Geometry',
    grade: '4',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g4-math-23',
    text: 'Identify the shape with 4 sides where opposite sides are equal.',
    options: ['Square', 'Rectangle', 'Triangle', 'Circle'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Geometry',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-24',
    text: 'Complete: 10, 20, 30, __, 50',
    options: ['35', '40', '45', '25'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Patterns',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-25',
    text: 'Complete: A, C, E, G, __',
    options: ['H', 'I', 'J', 'F'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Patterns',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-26',
    text: 'How many wheels do 4 tricycles have?',
    options: ['7', '10', '12', '9'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Multiplication',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-27',
    text: 'A box holds 10 pencils. How many pencils in 5 boxes?',
    options: ['15', '50', '55', '2'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Multiplication',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-28',
    text: 'Tom has 50 rupees. He buys a pen for 20 rupees. How much is left?',
    options: ['20', '30', '70', '80'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Money',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-29',
    text: 'I am a number. If you add 10 to me, I become 20. Who am I?',
    options: ['30', '20', '10', '5'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Algebra',
    grade: '4',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g4-math-30',
    text: 'Which is heavier: 1kg of cotton or 1kg of iron?',
    options: ['Iron', 'Cotton', 'Both are equal', 'None'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'Math',
    damage: 35
  },
  {
    id: 'g4-math-31',
    text: '300 + 40 + 5 = ?',
    options: ['345', '3045', '300405', '354'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Numbers',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-32',
    text: '56 ÷ 7 = ?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Division',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-33',
    text: 'How many corners does a Triangle have?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Geometry',
    grade: '4',
    subject: 'Math',
    damage: 15
  },
  {
    id: 'g4-math-34',
    text: 'If yesterday was Friday, tomorrow is?',
    options: ['Saturday', 'Sunday', 'Monday', 'Tuesday'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Time',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-35',
    text: 'Arrange in ascending order: 10, 5, 20, 2',
    options: ['20, 10, 5, 2', '2, 5, 10, 20', '2, 5, 20, 10', '5, 2, 10, 20'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Numbers',
    grade: '4',
    subject: 'Math',
    damage: 20
  },
  {
    id: 'g4-math-36',
    text: 'I am a 3-digit number. Ones digit is 5. Tens is 2 more than Ones. Hundreds is 1 less than Tens. Who am I?',
    options: ['675', '575', '755', '672'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'Math',
    damage: 40
  },
  {
    id: 'g4-math-38',
    text: 'A movie started at 4:30 PM. It was 2 hours and 30 minutes long. When did it end?',
    options: ['6:30 PM', '6:00 PM', '7:00 PM', '7:30 PM'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Time',
    grade: '4',
    subject: 'Math',
    damage: 35
  },
  {
    id: 'g4-math-39',
    text: 'If 1 Triangle = 3 Circles, and 1 Circle = 2 Squares. How many Squares is 1 Triangle equal to?',
    options: ['3', '5', '6', '9'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'Math',
    damage: 40
  },
  {
    id: 'g4-math-40',
    text: 'Find the Odd One Out: 24, 32, 18, 17',
    options: ['24', '32', '18', '17'],
    correctAnswer: 3,
    difficulty: 3,
    skill: 'Even/Odd',
    grade: '4',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g4-math-41',
    text: 'A pencil costs ₹5. A pen costs ₹10. I have ₹40. Max items I can buy (at least one of each)?',
    options: ['8', '7', '6', '5'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Money Logic',
    grade: '4',
    subject: 'Math',
    damage: 40
  },
  {
    id: 'g4-math-42',
    text: 'Look at the pattern: 1, 2, 4, 7, 11, __',
    options: ['15', '16', '14', '18'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Patterns',
    grade: '4',
    subject: 'Math',
    damage: 40
  },
  {
    id: 'g4-math-43',
    text: 'Which is greater: 1/2 of a Pizza or 1/4 of two Pizzas?',
    options: ['1/2 of one', '1/4 of two', 'They are equal', 'Cannot say'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Fractions',
    grade: '4',
    subject: 'Math',
    damage: 40
  },
  {
    id: 'g4-math-44',
    text: 'If you write numbers from 1 to 20, how many times do you write the digit "1"?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Counting',
    grade: '4',
    subject: 'Math',
    damage: 40
  },
  {
    id: 'g4-math-45',
    text: 'Tom is 4th from the left in a line. He is also 4th from the right. How many people are in the line?',
    options: ['8', '9', '7', '6'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'Math',
    damage: 35
  },
  {
    id: 'g4-math-46',
    text: 'Use digits 1, 2, 3 to make a 3-digit number. You cannot use a digit twice. How many numbers can you make?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 3,
    difficulty: 3,
    skill: 'Combinations',
    grade: '4',
    subject: 'Math',
    damage: 40
  },
  {
    id: 'g4-math-47',
    text: 'What is (10 × 0) + 10?',
    options: ['0', '10', '20', '100'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Operations',
    grade: '4',
    subject: 'Math',
    damage: 30
  },
  {
    id: 'g4-math-48',
    text: 'I have 40 legs in my farm. I have only Cows and Hens. If I have 10 heads, how many Cows do I have?',
    options: ['10 Cows', '5 Cows', '0 Cows', 'Impossible'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'Math',
    damage: 50
  },
  {
    id: 'g4-math-49',
    text: 'Which date is impossible?',
    options: ['30 February', '31 January', '1 March', '29 February'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Calendar',
    grade: '4',
    subject: 'Math',
    damage: 25
  },
  {
    id: 'g4-math-50',
    text: 'A box weighs 1kg empty. We put 5 books inside. Each book weighs 500g. Total weight?',
    options: ['2.5kg', '3.5kg', '3kg', '6kg'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Measurement',
    grade: '4',
    subject: 'Math',
    damage: 35
  },

  // --- SCIENCE ---
  {
    id: 'g4-sci-1',
    text: 'Which part of the plant makes food?',
    options: ['Root', 'Stem', 'Leaf', 'Flower'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Plants',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-2',
    text: 'Which animal lives both on land and in water?',
    options: ['Fish', 'Frog', 'Monkey', 'Eagle'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Animals',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-3',
    text: 'What do birds use to eat?',
    options: ['Teeth', 'Beak', 'Lips', 'Tongue'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Birds',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-4',
    text: 'Humans breathe in Oxygen and breathe out...',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Air'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Human Body',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-5',
    text: 'Which of these is a Herbivore?',
    options: ['Lion', 'Dog', 'Cow', 'Cat'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Animals',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-6',
    text: 'Which sense organ helps you feel hot or cold?',
    options: ['Eyes', 'Nose', 'Skin', 'Ears'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Senses',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-7',
    text: 'A seed needs air, water, and _____ to grow.',
    options: ['Darkness', 'Warmth/Sunlight', 'Cold', 'Rocks'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-8',
    text: 'Which of these can flow?',
    options: ['Book', 'Water', 'Pencil', 'Stone'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Matter',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-9',
    text: 'Steam is water in which form?',
    options: ['Solid', 'Liquid', 'Gas', 'Ice'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'States of Matter',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-10',
    text: 'Which material is waterproof?',
    options: ['Cotton', 'Paper', 'Plastic', 'Tissue'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Materials',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-11',
    text: 'Which object will float on water?',
    options: ['Iron nail', 'Stone', 'Plastic Ball', 'Coin'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Materials',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-12',
    text: 'The Sun is a...',
    options: ['Planet', 'Star', 'Satellite', 'Rock'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Space',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-13',
    text: 'Which planet is closest to the Sun?',
    options: ['Earth', 'Venus', 'Mercury', 'Mars'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Space',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-14',
    text: 'Why do we have day and night?',
    options: ['The Sun sleeps', 'The Earth rotates', 'Moon covers Sun', 'Clouds block light'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Space',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-15',
    text: 'What gives us heat and light during the day?',
    options: ['Moon', 'Sun', 'Stars', 'Fire'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Space',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-16',
    text: 'To open a door, you either Push or _____ it.',
    options: ['Hit', 'Pull', 'Jump', 'Run'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Force',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-17',
    text: 'Which is a simple machine?',
    options: ['Computer', 'Scissor', 'TV', 'Mobile'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Machines',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-18',
    text: 'Moving air is called...',
    options: ['Storm', 'Wind', 'Rain', 'Cloud'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Weather',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-19',
    text: 'Friction helps us to...',
    options: ['Fly', 'Slip', 'Walk without falling', 'Float'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Force',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-20',
    text: 'Which organ pumps blood?',
    options: ['Brain', 'Lungs', 'Heart', 'Stomach'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Human Body',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-21',
    text: 'We should brush our teeth...',
    options: ['Once a week', 'Twice a day', 'Once a month', 'Never'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Hygiene',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-22',
    text: 'The skeleton is made of...',
    options: ['Muscles', 'Skin', 'Bones', 'Blood'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Human Body',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-23',
    text: 'Which food gives energy?',
    options: ['Water', 'Rice/Roti', 'Salt', 'Medicine'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Nutrition',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-24',
    text: 'Birds build nests to...',
    options: ['Sleep only', 'Lay eggs & protect babies', 'Store food', 'Play'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Birds',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-25',
    text: 'A dog\'s baby is called a...',
    options: ['Kitten', 'Cub', 'Puppy', 'Calf'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Animals',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-26',
    text: 'Animals that chew cud (like Cows) eat...',
    options: ['Fast', 'Only at night', 'Swallow first, chew later', 'Meat'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Animals',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-27',
    text: 'An insect has ___ legs.',
    options: ['2', '4', '6', '8'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Insects',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-28',
    text: 'We should throw garbage in...',
    options: ['The river', 'The street', 'The dustbin', 'The park'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Environment',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-29',
    text: 'Which vehicle does not need fuel?',
    options: ['Car', 'Bicycle', 'Bus', 'Bike'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Transport',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-30',
    text: 'Water vapor turning back into water is called...',
    options: ['Evaporation', 'Condensation', 'Melting', 'Freezing'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Water Cycle',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-31',
    text: 'Which is a safety rule?',
    options: ['Play with fire', 'Run on road', 'Cross at Zebra crossing', 'Touch wires'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Safety',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-32',
    text: 'Soil is made of...',
    options: ['Plastic', 'Rocks, sand, humus', 'Metal', 'Air only'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Earth',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-33',
    text: 'A rainbow has ___ colors.',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Nature',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-34',
    text: 'Identify the Creeper plant:',
    options: ['Mango Tree', 'Pumpkin', 'Rose', 'Tulsi'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Plants',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-35',
    text: 'What is the main source of light on Earth?',
    options: ['Moon', 'Sun', 'Bulb', 'Fire'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Space',
    grade: '4',
    subject: 'Science',
    damage: 15
  },
  {
    id: 'g4-sci-36',
    text: 'If you put a plant in a dark box with a small hole, it grows towards the hole. Why?',
    options: ['To see outside', 'Needs sunlight to live', 'Accidental', 'Likes holes'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Plants',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-37',
    text: 'Why can a duck float but a chicken cannot?',
    options: ['Duck is lighter', 'Webbed feet & oily feathers', 'Chicken is afraid', 'Duck drinks water'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Animals',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-38',
    text: 'If the Sun moves to the Right side, where will the shadow go?',
    options: ['Right side', 'Left side', 'Disappear', 'Stay same'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Light',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-39',
    text: 'Which glass of water will dry faster?',
    options: ['In fridge', 'In sun', 'In cupboard', 'In room'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Evaporation',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-40',
    text: 'If all lions die in a forest, what happens to the deer?',
    options: ['Deer get sad', 'Deer population increases', 'Deer die too', 'Nothing'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Ecosystem',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-41',
    text: 'You have a mixture of Sand and Iron filings. How do you separate them?',
    options: ['Hand picking', 'Using a Magnet', 'Filtering', 'Heating'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Separation',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-42',
    text: 'Why do we see lightning before we hear thunder?',
    options: ['Eyes faster than ears', 'Light travels faster than sound', 'Thunder is later', 'Magic'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Light/Sound',
    grade: '4',
    subject: 'Science',
    damage: 40
  },
  {
    id: 'g4-sci-43',
    text: 'A balloon gets bigger when you blow into it because...',
    options: ['Rubber stretches automatically', 'Air takes up space', 'It becomes hot', 'It becomes heavy'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Air',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-44',
    text: 'Which of these is NOT an insect?',
    options: ['Ant', 'Spider', 'Mosquito', 'Butterfly'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Animals',
    grade: '4',
    subject: 'Science',
    damage: 35
  },
  {
    id: 'g4-sci-45',
    text: 'Why do desert plants (Cactus) have thorns instead of leaves?',
    options: ['To hurt animals', 'To save water', 'Look scary', 'No sun'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Adaptation',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-46',
    text: 'If you put a steel spoon in hot tea, the handle becomes hot. Why?',
    options: ['Spoon creates heat', 'Heat travels from tea to spoon', 'Spoon melting', 'Air heats it'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Heat',
    grade: '4',
    subject: 'Science',
    damage: 30
  },
  {
    id: 'g4-sci-47',
    text: 'Which planet is called the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Space',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-48',
    text: 'Identify the odd one out: Car, Bus, Truck, Train.',
    options: ['Car', 'Bus', 'Train', 'Truck'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'Science',
    damage: 25
  },
  {
    id: 'g4-sci-49',
    text: 'Why do we have bones?',
    options: ['To weigh more', 'Shape and support', 'Make blood', 'Fill space'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Human Body',
    grade: '4',
    subject: 'Science',
    damage: 20
  },
  {
    id: 'g4-sci-50',
    text: 'Water drops inside a tied plastic bag over a plant. Why?',
    options: ['Bag leaking', 'Plants release water (Transpiration)', 'Air has water', 'Magic'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Plants',
    grade: '4',
    subject: 'Science',
    damage: 40
  },

  // --- ENGLISH ---
  {
    id: 'g4-eng-1',
    text: 'Choose the Noun: "The happy boy ran fast."',
    options: ['Happy', 'Ran', 'Boy', 'Fast'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-2',
    text: 'Plural of "Child":',
    options: ['Childs', 'Children', 'Childrens', 'Childes'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-3',
    text: 'Past tense of "Go":',
    options: ['Goed', 'Gone', 'Went', 'Going'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-4',
    text: 'She _____ a beautiful song yesterday.',
    options: ['Sing', 'Sang', 'Sung', 'Sings'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-5',
    text: 'Choose the Adjective: "The tall tree."',
    options: ['The', 'Tall', 'Tree', 'None'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-6',
    text: 'Opposite of "Heavy":',
    options: ['Hard', 'Small', 'Light', 'Soft'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-7',
    text: 'Is this a complete sentence? "Running to the store."',
    options: ['Yes', 'No'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Sentences',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-8',
    text: '_____ sun is hot.',
    options: ['A', 'An', 'The', 'Two'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Articles',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-9',
    text: 'The cat jumped _____ the table.',
    options: ['In', 'On', 'At', 'Of'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Prepositions',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-10',
    text: 'Use "An" before:',
    options: ['Ball', 'Apple', 'Cat', 'Dog'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Articles',
    grade: '4',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g4-eng-11',
    text: 'Which mark ends a question?',
    options: ['.', '!', '?', ','],
    correctAnswer: 2,
    difficulty: 1,
    skill: 'Punctuation',
    grade: '4',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g4-eng-12',
    text: 'Find the correct spelling:',
    options: ['Becoz', 'Because', 'Becuase', 'Beecos'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Spelling',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-13',
    text: 'Capitalize: "i live in india."',
    options: ['I Live In India.', 'I live in India.', 'i live in India.', 'I live in india.'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-14',
    text: 'A person who cures sick people is a...',
    options: ['Teacher', 'Doctor', 'Pilot', 'Baker'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g4-eng-15',
    text: '"See" and "Sea" are...',
    options: ['Antonyms', 'Synonyms', 'Homophones', 'Verbs'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-16',
    text: 'Synonym for "Big":',
    options: ['Tiny', 'Huge', 'Small', 'Short'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-17',
    text: 'Choose the correct word: "I write with my _____ hand."',
    options: ['Right', 'Write'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-18',
    text: 'Identify the Pronoun: "Ravi is happy because he won."',
    options: ['Ravi', 'Happy', 'He', 'Won'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-19',
    text: 'Comparative degree: "This box is _____ than that one."',
    options: ['Heavy', 'Heavier', 'Heaviest', 'More heavy'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-20',
    text: 'Which word is a compound word?',
    options: ['Happy', 'Sunlight', 'Running', 'Faster'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-21',
    text: 'Rearrange: is / name / My / Tom.',
    options: ['Name is My Tom.', 'My name is Tom.', 'Tom my name is.', 'Is name Tom My.'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Sentences',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-22',
    text: 'Conjunction: "I like milk _____ I don\'t like tea."',
    options: ['And', 'But', 'So', 'Or'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-23',
    text: '"The dog barked loudly." "Loudly" describes the...',
    options: ['Dog', 'Barked'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-24',
    text: 'Gender: King is to Queen, as Boy is to...',
    options: ['Man', 'Girl', 'Lady', 'Woman'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g4-eng-25',
    text: '"A group of lions" is called a...',
    options: ['Herd', 'Pride', 'Pack', 'Flock'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-26',
    text: '"Tina forgot her umbrella. She got wet." Why did she get wet?',
    options: ['She likes rain', 'She had no umbrella', 'She swam', 'She cried'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Reading',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-27',
    text: '"The sun set and the stars came out." What time is it?',
    options: ['Morning', 'Afternoon', 'Night', 'Noon'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Reading',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-28',
    text: 'Which word means "Very Cold"?',
    options: ['Hot', 'Freezing', 'Warm', 'Cool'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-29',
    text: 'Rhyme: Bat, Cat, Mat, ...',
    options: ['Dog', 'Sat', 'Car', 'Ball'],
    correctAnswer: 1,
    difficulty: 1,
    skill: 'Rhyme',
    grade: '4',
    subject: 'English',
    damage: 15
  },
  {
    id: 'g4-eng-30',
    text: '"Do not run." This sentence is a...',
    options: ['Question', 'Order/Command', 'Statement', 'Surprise'],
    correctAnswer: 1,
    difficulty: 2,
    skill: 'Sentences',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-31',
    text: 'Plural of "Mouse":',
    options: ['Mouses', 'Mice', 'Mouse', 'Meese'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-32',
    text: '"This is _____ book." (Belonging to me)',
    options: ['I', 'Mine', 'My', 'Me'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-33',
    text: 'Prefix for "Happy" to make it opposite:',
    options: ['Un', 'Dis', 'Im', 'Re'],
    correctAnswer: 0,
    difficulty: 2,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-34',
    text: '"They _____ playing football." (Present Continuous)',
    options: ['Is', 'Am', 'Are', 'Was'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-35',
    text: 'Correct order: A / red / big / ball',
    options: ['A red big ball', 'A big red ball', 'A ball big red', 'Ball a red big'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Adjectives',
    grade: '4',
    subject: 'English',
    damage: 30
  },
  // --- CHALLENGE ENGLISH ---
  {
    id: 'g4-eng-36',
    text: 'Find the Odd One Out: Run, Jump, Fast, Swim.',
    options: ['Run', 'Jump', 'Fast', 'Swim'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-37',
    text: '"I saw a man eating shark." vs "I saw a man eating, Shark." What changes the meaning?',
    options: ['Spelling', 'Punctuation', 'Verb', 'Nothing'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Punctuation',
    grade: '4',
    subject: 'English',
    damage: 35
  },
  {
    id: 'g4-eng-38',
    text: 'Analogy: Finger is to Hand as Leaf is to...',
    options: ['Tree', 'Flower', 'Branch', 'Root'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g4-eng-39',
    text: 'Which word can mean "A place to put money" AND "The side of a river"?',
    options: ['Coast', 'Bank', 'Store', 'Edge'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Vocabulary',
    grade: '4',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g4-eng-40',
    text: '"The car stopped." Make this sentence more descriptive.',
    options: ['The car is red.', 'The car stopped suddenly.', 'The car goes.', 'Stop the car.'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Writing',
    grade: '4',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g4-eng-41',
    text: 'If "Un-tie" means to open a knot, what does "Re-tie" mean?',
    options: ['Tie again', 'Not tie', 'Tie badly', 'Open'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Prefixes',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-42',
    text: '"I bought a bat." What is the confusion here?',
    options: ['Spelling error', 'Animal vs Sports item', 'Wrong grammar', 'No confusion'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Homonyms',
    grade: '4',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g4-eng-43',
    text: 'Arrange to make a story: 1. He ate apple. 2. He washed it. 3. He bought apple.',
    options: ['1, 2, 3', '3, 2, 1', '3, 1, 2', '2, 3, 1'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-44',
    text: '"The cake was eaten by Tom." Change to Active.',
    options: ['Tom is eating cake.', 'Tom ate the cake.', 'Cake ate Tom.', 'Tom was eating.'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 35
  },
  {
    id: 'g4-eng-45',
    text: 'Which sentence is polite?',
    options: ['Give me water.', 'I want water.', 'May I have water?', 'Get water.'],
    correctAnswer: 2,
    difficulty: 2,
    skill: 'Manners',
    grade: '4',
    subject: 'English',
    damage: 20
  },
  {
    id: 'g4-eng-46',
    text: '"She has _____ friends than me." (Countable)',
    options: ['Less', 'Fewer', 'Lesser', 'Little'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Grammar',
    grade: '4',
    subject: 'English',
    damage: 35
  },
  {
    id: 'g4-eng-47',
    text: 'What is silent in the word "Honest"?',
    options: ['o', 'n', 'H', 't'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Spelling',
    grade: '4',
    subject: 'English',
    damage: 25
  },
  {
    id: 'g4-eng-48',
    text: '"It\'s raining cats and dogs." What does this mean?',
    options: ['Animals are falling', 'Raining heavily', 'Cats are barking', 'It is a joke'],
    correctAnswer: 1,
    difficulty: 3,
    skill: 'Idioms',
    grade: '4',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g4-eng-49',
    text: 'Choose the word that does not fit: Table, Chair, Furniture, Sofa.',
    options: ['Table', 'Chair', 'Furniture', 'Sofa'],
    correctAnswer: 2,
    difficulty: 3,
    skill: 'Logic',
    grade: '4',
    subject: 'English',
    damage: 30
  },
  {
    id: 'g4-eng-50',
    text: '"Yesterday, tomorrow will be...?"',
    options: ['Today', 'Sunday', 'Past', 'Future'],
    correctAnswer: 0,
    difficulty: 3,
    skill: 'Riddle',
    grade: '4',
    subject: 'English',
    damage: 35
  }
];
